name: evaluate nix store paths

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: build system
        run: |
          nix eval .#packages.x86_64-linux.default
          nix eval .#packages.x86_64-linux.maintenance
          nix eval .#packages.x86_64-linux.test-image
